version: '3'
services:
  redis:
    image: 'redis:alpine'
    hostname: redis
    
  api:
    build: .
    ports:
     - "80:5001"
    environment:
      - APP_ENV=${APP_ENV}
    links:
      - redis
    depends_on:
      - redis

  api-worker:
    build: .
    command: celery -A tasks.celery worker --loglevel=info --uid celery
    environment:
      - APP_ENV=${APP_ENV}
    links:
      - redis
