version: '3'
services:
  redis:
    image: 'redis:alpine'
    hostname: redis
    networks:
      - waterline
  api:
    build: .
    ports:
     - "80:5001"
    environment:
      - APP_ENV=${APP_ENV}
    links:
      - redis
    depends_on:
      - redis
    networks:
      - waterline

  api-worker:
    build: .
    command: celery -A tasks.celery worker --loglevel=info --uid celery
    environment:
      - APP_ENV=${APP_ENV}
    links:
      - redis
    networks:
      - waterline

networks:
  waterline:
    external: true
  
