apiVersion: v1
kind: Service
metadata:
  namespace: metadata
  labels:
    nameLabel: celery-worker
  name: celery-worker
spec:
  ports:
    - name: "5555"
      port: 5555
      targetPort: 5555
  selector:
    nameLabel: celery-worker
status:
  loadBalancer: {}
