apiVersion: v1
kind: Service
metadata:
  namespace: metadata
  labels:
    nameLabel: metadata-svc
  name: metadata-svc
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 5001
  selector:
    nameLabel: metadata-svc
status:
  loadBalancer: {}
